name: Static Analysis

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  tests:
    name: Run tests
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3, 8.2 ]
        laravel: [ 11.*, 10.* ]
        include:
          - laravel: 11.*
            orchestra: 9.*
          - laravel: 10.*
            orchestra: 8.*

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php  }}'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      # <!--DELETE-->
      - name: Initialize Plugin
        run: |
          ./plugin init asciito filament-plugin-test "Ayax Córdova" example@mail.com "This is a short description" --no-interaction
      # <!--/DELETE-->

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.orchestra }}" "php:^${{ matrix.php }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Run Static Analysis
        run: vendor/bin/phpstan --error-format=github
