name: Static Analysis

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  tests:
    name: Run tests
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.2, 8.1 ]
        laravel: [ 10.* ]
        include:
          - laravel: 10.*
            carbon: 2.*

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.version  }}'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      # Remove when plugin is initialized
      - name: Initialize Plugin
        run: |
          ./package init:plugin asciito filament-plugin-test --dont-delete-cli

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "nesbot/carbon:${{ matrix.carbon }}" "php:^${{ matrix.php }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan --error-format=github
